import { root } from "../app.js";
const loginForm = () => { 

  const headerTitle = document.createElement('h1');
  root.append(headerTitle);
  headerTitle.className = 'header-title';
  headerTitle.innerText = 'Login';
  const container = document.createElement('div');
  container.className = 'container';
  root.append(container);
  const form = document.createElement('form');
  form.id = 'form';
  container.append(form);
  const usernameLabel = document.createElement('label');
  usernameLabel.className = 'username-label';
  usernameLabel.for = 'username';
  usernameLabel.innerText = 'Username : ';
  form.append(usernameLabel);
  const usernameInput = document.createElement('input');
  usernameInput.type = 'text';
  usernameInput.placeholder = 'username';
  usernameInput.className = 'inputs';
  usernameInput.id = 'username';
  form.append(usernameInput);
  const usernameMessage = document.createElement('p');
  usernameMessage.className = 'username-message';
  form.append(usernameMessage);
  const ageLabel = document.createElement('label');
  ageLabel.className = 'age-label';
  ageLabel.for = 'age';
  ageLabel.innerText = 'Age : ';
  form.append(ageLabel);
  const ageInput = document.createElement('input');
  ageInput.className = 'inputs';
  ageInput.id = 'age';
  ageInput.type = 'number';
  ageInput.placeholder = 'age';
  form.append(ageInput);
  const ageMessage = document.createElement('p');
  ageMessage.className = 'age-message';
  form.append(ageMessage);
  const passwordLabel = document.createElement('label');
  passwordLabel.for = 'password';
  passwordLabel.innerText = 'Password : ';
  form.append(passwordLabel);
  const passwordInput = document.createElement('input');
  passwordInput.className = 'inputs';
  passwordInput.id = 'password';
  passwordInput.type = 'password';
  passwordInput.placeholder = 'password';
  form.append(passwordInput);
  const passwordMessage = document.createElement('p');
  passwordMessage.className = 'password-message';
  form.append(passwordMessage);
  const confirmPasswordLabel = document.createElement('label');
  confirmPasswordLabel.for = 'confirm-password';
  confirmPasswordLabel.innerText = 'Confirm Password : ';
  form.append(confirmPasswordLabel);
  const confirmPasswordInput = document.createElement('input');
  confirmPasswordInput.className = 'inputs';
  confirmPasswordInput.id = 'confirm-password';
  confirmPasswordInput.type = 'password';
  confirmPasswordInput.placeholder = 'confirm password';
  form.append(confirmPasswordInput);
  const confirmPasswordMessage = document.createElement('p');
  confirmPasswordMessage.className = 'confirm-password-message';
  form.append(confirmPasswordMessage);
  const emailLabel = document.createElement('label');
  emailLabel.for = 'email';
  emailLabel.innerText = 'Email : ';
  form.append(emailLabel);
  const emailInput = document.createElement('input');
  emailLabel.className = 'inputs';
  emailInput.id = 'email';
  emailInput.type = 'text';
  emailInput.placeholder = 'email';
  form.append(emailInput);
  const emailMessage = document.createElement('p');
  emailMessage.className = 'email-message';
  form.append(emailMessage);
  const submit = document.createElement('input');
  submit.className = 'submit';
  submit.type = 'submit';
  form.append(submit);
  
};
export default loginForm;